### ISSUE TITLE
Strike notifications

### ISSUE THREAD

**Issue by Snowda** [thecosmicfrog/LuasataGlance#13]
Give people a notification that there will be a strike soon if they have used the App recently. Preferably the day before so that people can make alternate plans. If the dates were held remotely in a basic JSON file (Github pages can be used to host for free) the dates could be queried without needing to update the app to match new future strikes.

**Comment by thecosmicfrog** [comment]
Hi @Snowda. Thanks for the feature request! I'll see if I can get some time and hack something together. This could be very useful for service disruptions beyond the strikes.

**Comment by thecosmicfrog** [comment]
Closing as it looks like there won't be any strikes in the near future (with any luck).

Thanks again @Snowda for the request!
