### ISSUE TITLE
appears that api is down

### ISSUE THREAD

**Issue by barrypearseburke** [thecosmicfrog/LuasataGlance#15]
I am not able to receive tram notification. Alerts also links to a dead page possibility indicating that luas changed their address.

**Comment by barrypearseburke** [comment]
Getting error app/web is offline for maintenance. Are you offline or is is just a bug?

**Comment by thecosmicfrog** [comment]
Hi @barrypearseburke,

Apologies for the delay in getting back. Yes indeed, the whole RTPI system was down until recently. It affected everything that uses it: Luas at a Glance and even the official Luas apps and website.

It seems to be working again now, thankfully. Apologies for the inconvenience - one of these things that was out of my hands I'm afraid. My side of things was all working as expected.

Thanks for reporting this though - I appreciate it! I'll mark this as closed.

All the best,
Aaron
