### ISSUE TITLE
Irish translations

### ISSUE THREAD

**Issue by marcasoduinn** [thecosmicfrog/LuasataGlance#18]
Hi there, it's fantastic to see an Irish version of the Luas timetable, i use it every day. Thanks for taking the initiative. 

I understand from your help screen that you contracted someone for the translations. Nonetheless, may i suggest some updates, for example:
* Aon tramanna ag súil ("one trams expecting") --> Tram at bith geallta [suggestion] 
* Aipp guthán --> Aip ghutháin
* etc.

It would be great too see these improvements, 
GRMA
Marcas

**Comment by marcasoduinn** [comment]
I found the XML file for the Irish translations. Rather than creating a fork in the database just yet, i downloaded a copy for myself to edit locally.  I also found some "translatable=false" entries on the English version, which I've integrated into my local Irish version. 

I intend to review my changes with a friend of mine, more fluent in Irish than I. Is Feidhlim still involved in the project?

**Comment by thecosmicfrog** [comment]
Hi @marcasoduinn,

Thanks a million for filing this issue. I'd be absolutely delighted to integrate any suggestions or changes you have.

Feidhlim is not actively involved in the project day-to-day, but he's a good friend whom I do run things past him the odd time. Being clumsy with Irish myself, I may be to blame for a good few of those mistranslations. The consequences of being in a rush without time to fully review, unfortunately!

If you know your way around Git, I recommend making the changes yourself and submitting a Pull Request against this repository. That way you'll get your own record as a contributor - but completely up to yourself. If you'd like to just send me a copy of the **strings.xml** I'm happy to merge it myself.

Thanks again for taking the time to comment here. Always great to receive feedback in any form!

Míle buíochas,
Aaron

**Comment by marcasoduinn** [comment]
Hi Aaron, it's great to see your enthusiasm.

I use SVN source control daily, and I've read a Git intro, so I'll start a
fork and issue a pull request when ready. In Git, is there a difference
between a "branch" and a "fork"?

I presume that the "translatable=false" attributes can be removed from the
English XML, once the translation exists in the Irish. I don't intend to
translate the revision notes, is that alright?

Marcas

**Comment by thecosmicfrog** [comment]
Hi @marcasoduinn - and yours too!

Ah excellent, so you're already adept with source control in that case! The primary difference with Git is that it's distributed versus SVN's centralised (client/server) model. A branch is more or less what you expect it to be from SVN, but it's more lightweight and lives on your machine until you "git push" it to the "remote" repo (GitHub in this case). A fork is a complete copy of a repo. There's probably no real need to use branches on your side. I only push one branch to GitHub myself (master) and leave all branches on my local machine for ad-hoc development and testing new features.

So the workflow here would be:

1. Fork my repo (thecosmicfrog/luasataglance). This will make one in your account called marcasoduinn/luasataglance.
2. "git clone" this to your local machine.
3. Make the appropriate changes.
4. "git add" the changed file.
5. Run "git commit" and enter a commit message explaining what you've changed. If you like, you can use the same format I've been using for my commit messages (run "git log"). A Git commit is a completely local concept - it doesn't talk to a server at all.
6. Run "git push" which will push your changes to the remote (GitHub).
7. Go to marcasoduinn/luasataglance on GitHub and create a Pull Request against my repo (likely master branch -> master branch).

I hope that makes sense!

Absolutely, you can remove translatable=false. It implicitly defaults to "true" anyway. No problem - no need to translate the revision notes.

Let me know if you have any questions!

All the best,
Aaron

**Comment by marcasoduinn** [comment]
Hi Aaron, just a quick note that I am on holidays for the next fortnight,
back at the beginning of August.  All files are obviously checked in.
Marcas


Ar Déar 12 Iúil 2018 ag 00:11, scríobh Aaron Hastings <
notifications@github.com>:

**Comment by thecosmicfrog** [comment]
Hi @marcasoduinn,

Not a bother. I've been busy myself over the past few days so please excuse my lateness in replying to your other issue!

Fantastic! I'll take a look now.

Have a great holiday and enjoy. Thanks again for putting so much time and effort on your part into this. It's great to make this a community effort in order to make a great app.

Mise le meas,
Aaron

**Comment by thecosmicfrog** [comment]
Hi again @marcasoduinn,

Left a comment on your Pull Request just now. I think you created against **your own master branch** instead of mine (easily done - no worries).

Let me know if I can help at all!

Cheers,
Aaron

**Comment by marcasoduinn** [comment]
Hi Aaron,
I'm back from holidays!

Yes, I did create my own branch... I thought that would be the safest thing
to do, but I that is "SVN" thinking, isn't it.  With github, I can safely
edit files "at one remove", and queue them for commital to the main
repository via a "pull request"... is that the philosophy?

So, if I complete the pull request to my own branch, can I then merge back
to your main branch?... and how?
Marcas


Ar Máirt 17 Iúil 2018 ag 21:54, scríobh Aaron Hastings <
notifications@github.com>:

**Comment by thecosmicfrog** [comment]
Hi @marcasoduinn,

Not a bother!

Absolutely; you can go ahead and accept your own Pull Request into your master branch. Then create a new Pull Request against my master branch (thecosmicfrog/LuasataGlance/master).

Let me know if I can help at all.
Aaron

**Comment by thecosmicfrog** [comment]
Going to mark this as resolved now, thanks to your contributions!

If you spot anything else, I'll be very happy to accept further Pull Requests.

Míle buíochas,
Aaron

**Comment by marcasoduinn** [comment]
That's great, Aaron, I'm looking out for the next update!

In the meantime, I've asked a friend to review the translations. If there
are changes from that, I'll leery you know cia a pull request.

Marcas
